name: devnet-replicate-change

on:
  push:
    branches:
      - main  # Trigger on pushes to template repo main branch
  workflow_dispatch:  # Also allow manual trigger

env:
  SOURCE_REPOSITORY: conterra/mapapps-devnet-blueprint  # Replace with your template repo full name
  TARGET_REPOS: |
    conterra/mapapps-bookmarks

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout the template repository
        uses: actions/checkout@v4

      - name: Sync to target repositories and create PRs
        uses: AndreasAugustin/actions-template-sync@v2
        with:
          github_token: ${{secrets.TECHNICAL_USER_RELEASE_TOKEN}}
          source_repo_path: ${{ env.SOURCE_REPOSITORY }}
          upstream_branch: main
          pr_title: "[Template Sync] Update from template repo"
          pr_commit_msg: "chore(template): sync changes from template repo"
          pr_labels: "template_sync"
